FROM postgres:13

RUN apt-get update && apt-get install -y \
    build-essential \
    postgresql-server-dev-13 \
    git

RUN git clone https://github.com/pgvector/pgvector.git /usr/local/src/pgvector && \
    cd /usr/local/src/pgvector && \
    make && make install

RUN rm -rf /var/lib/apt/lists/* /usr/local/src/pgvector
